name: UPDATE_APP_ACTION

on:
  push:
    branches:
      - main
jobs:
  update-readme-with-appinfo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          ETH_API_KEY: ${{secrets.ETH_API_KEY}}
