name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        env:
          ETH_API_KEY: ${{ secrets.ETH_API_KEY }}
